cc_test(
    name = "digest_test",
    srcs = [
        "digest_test.cc",
    ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//book:digest",
        "@gtest//:main",
    ],
)

cc_test(
    name = "asn1_test",
    srcs = [
        "asn1_test.cc",
    ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//book:asn1",
        "@gtest//:main",
    ],
)
